[k8s_master]
k8s-master ansible_host=158.160.50.135 ansible_user=ubuntu

[k8s_workers]
k8s-worker-1 ansible_host=51.250.2.76 ansible_user=ubuntu
k8s-worker-2 ansible_host=158.160.40.21 ansible_user=ubuntu

[k8s_cluster:children]
k8s_master
k8s_workers
